export const technicianWorkspaceStyles = {
  shell:
    'min-h-screen bg-[#f8fafe] font-sans text-[13px] text-[#171c1f] lg:grid lg:grid-cols-[260px_minmax(0,1fr)] lg:overflow-hidden',
  sidebar:
    'flex min-h-screen flex-col bg-[#001d32] text-white lg:h-screen lg:overflow-hidden',
  sidebarHeader: 'border-b border-white/10 px-4 pb-6 pt-4',
  logoMark:
    'flex h-[34px] w-[34px] shrink-0 items-center justify-center overflow-hidden rounded-lg bg-[#006096] shadow-[0_2px_8px_rgba(0,96,150,0.3)]',
  nav: 'flex min-h-0 flex-1 flex-col gap-1 overflow-y-auto px-3 py-4',
  navSection: 'px-3 py-1 text-[10px] font-bold uppercase tracking-[1px] text-white/35',
  navItem:
    'flex min-h-11 w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left text-[13.5px] font-medium text-white/65 transition hover:bg-white/10 focus:outline-none focus:ring-2 focus:ring-cyan-300/50',
  navItemActive:
    'border-l-4 border-[#22d3ee] bg-[#263f51] pl-4 font-semibold text-white shadow-[0_1px_2px_rgba(0,0,0,0.05)]',
  navIcon: 'h-5 w-5 shrink-0',
  sidebarFooter: 'flex items-center gap-3 border-t border-white/10 bg-black/20 px-4 py-4',
  workspace: 'flex min-h-screen min-w-0 flex-col overflow-hidden lg:h-screen',
  topbar:
    'flex min-h-14 shrink-0 items-center justify-between gap-4 border-b border-[#bfc7d2] bg-white px-6',
  content: 'min-h-0 flex-1 overflow-auto',
  footer:
    'flex h-8 shrink-0 items-center justify-end border-t border-[#c0c7d1] bg-[#f2f3f8] px-6 text-[10px] text-[rgba(65,71,79,0.45)]',
  card:
    'overflow-hidden rounded-2xl border border-[#bfc7d2] bg-white shadow-[0_2px_12px_rgba(0,96,150,0.08)]',
  cardHeader: 'flex items-center justify-between gap-2 border-b border-[#e4e9ed] px-6 py-4',
  cardTitle: 'flex items-center gap-1.5 text-[14px] font-bold text-[#171c1f]',
  cardBody: 'p-6',
  sectionTitle: 'text-[12px] font-bold uppercase tracking-[1.2px] text-[#006096]',
  searchInputWrap: 'relative flex-1 min-w-[200px]',
  searchInput:
    'min-h-[48px] w-full rounded-lg border-[1.5px] border-[#bfc7d2] bg-white pl-10 pr-3.5 text-[13.5px] text-[#171c1f] outline-none transition-colors focus:border-[#006096]',
  selectField:
    'min-h-[48px] rounded-lg border-[1.5px] border-[#bfc7d2] bg-white px-3.5 text-[13.5px] text-[#171c1f] outline-none transition-colors focus:border-[#006096] cursor-pointer',
  iconButton:
    'inline-flex h-10 w-10 shrink-0 items-center justify-center rounded-lg border border-[#bfc7d2] bg-[#f8fafc] text-[#3f4851] transition hover:bg-[#eaeef2] focus:outline-none focus:ring-4 focus:ring-[#006096]/10',
  primaryButton:
    'inline-flex h-10 shrink-0 items-center justify-center gap-2 rounded-lg bg-[#007abc] px-4 text-[12px] font-bold text-white shadow-hms-button transition hover:bg-[#006096] focus:outline-none focus:ring-4 focus:ring-[#006096]/20',
  secondaryButton:
    'inline-flex h-10 shrink-0 items-center justify-center gap-2 rounded-lg border border-[#bfc7d2] bg-white px-4 text-[12px] font-bold text-[#374151] shadow-[0_1px_2px_rgba(0,0,0,0.05)] transition hover:bg-[#f2f3f8] focus:outline-none focus:ring-4 focus:ring-[#006096]/10',
  screenHeader: 'mb-6 flex flex-wrap items-start justify-between gap-2',
  screenTitle: 'text-[22px] font-bold leading-tight text-[#171c1f]',
  screenSubtitle: 'mt-0.5 text-[13px] text-[#3f4851]',
  screenActions: 'flex flex-wrap items-center gap-2',
  btn: 'inline-flex min-h-[48px] items-center justify-center gap-2 rounded-lg px-5 text-[13.5px] font-semibold transition-all active:scale-[0.98] disabled:opacity-50 whitespace-nowrap',
  btnSm: 'min-h-[40px] px-3.5 text-[12.5px]',
  btnLg: 'min-h-[52px] px-7 text-[15px]',
  btnPrimary: 'border-none bg-[#006096] text-white hover:bg-[#004a75]',
  btnSecondary: 'border-[1.5px] border-[#006096] bg-transparent text-[#006096] hover:bg-[#cee5ff]',
  btnGhost: 'border border-[#bfc7d2] bg-[#f0f4f8] text-[#3f4851] hover:bg-[#eaeef2]',
  btnErrorOutline: 'border-[1.5px] border-[#ba1a1a] bg-transparent text-[#ba1a1a] hover:bg-[#ffdad6]',
  badge: 'inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[11px] font-semibold whitespace-nowrap leading-none',
  badgeDot: 'h-1.5 w-1.5 rounded-full shrink-0',
  badgePending: 'bg-[#fff8e1] text-[#a05c00]',
  badgePaid: 'bg-[#d4f4e2] text-[#1a7a4a]',
  badgeWriteoff: 'bg-[#ffdad6] text-[#ba1a1a]',
  badgeNgoaitru: 'bg-[#e3f2fd] text-[#1565c0]',
  badgeNoitru: 'bg-[#ede7f6] text-[#4527a0]',
  signStampBadge: 'inline-flex items-center gap-1 rounded border-[1.5px] border-[#ba1a1a] bg-[#fff0f0] px-2 py-0.5 text-[11px] font-bold tracking-[0.5px] text-[#ba1a1a]',
  chipBar: 'flex flex-wrap gap-1.5',
  chip: 'inline-flex min-h-[40px] items-center gap-1.5 rounded-full border-[1.5px] border-[#bfc7d2] bg-transparent px-4 text-[12.5px] font-medium text-[#3f4851] transition-all hover:border-[#006096] hover:text-[#006096] active:scale-[0.97]',
  chipActive: 'border-[#006096] bg-[#006096] text-white hover:text-white',
  dataTableWrap: 'w-full overflow-x-auto',
  dataTable: 'w-full border-collapse text-left text-[13px]',
  th: 'border-b border-[#e4e9ed] bg-[#f0f4f8] px-3 py-2.5 text-[11.5px] font-bold uppercase tracking-[0.3px] text-[#3f4851]',
  td: 'border-b border-[#f0f4f8] px-3 py-2.5 align-middle',
  tr: 'transition-colors hover:bg-[#f0f4f8]',
  alert: 'mb-4 flex items-start gap-2.5 rounded-lg p-4 text-[13px] leading-relaxed',
  alertError: 'border border-[#f5c6c6] bg-[#ffdad6] text-[#ba1a1a]',
  alertInfo: 'border border-[#bfdbfe] bg-[#dbeafe] text-[#004e8c]',
  alertWarning: 'border border-[#fcd9a0] bg-[#ffecd4] text-[#a05c00]',
  modalOverlay: 'fixed inset-0 z-50 flex items-center justify-center bg-[#171c1f]/55 p-6 backdrop-blur-[2px]',
  modal: 'w-full max-w-[520px] overflow-hidden rounded-3xl bg-white shadow-[0_8px_40px_rgba(0,0,0,0.18)]',
  modalHeader: 'flex items-center gap-3 border-b border-[#e4e9ed] p-6 pb-4',
  modalTitle: 'text-[16px] font-bold leading-tight text-[#171c1f]',
  modalSub: 'mt-0.5 text-[12px] text-[#3f4851]',
  modalBody: 'p-6',
  modalFooter: 'flex justify-end gap-2 border-t border-[#e4e9ed] px-6 py-4',
  modalIcon: 'flex h-9 w-9 shrink-0 items-center justify-center rounded-xl',
  modalIconPrimary: 'bg-[#cee5ff] text-[#006096]',
  modalIconError: 'bg-[#ffdad6] text-[#ba1a1a]',
  modalChecklist: 'mb-4 space-y-2 text-[13px] text-[#171c1f]',
  modalChecklistItem: 'flex items-center gap-2 rounded-lg bg-[#f0f4f8] p-3 text-[13px] text-[#171c1f]',
  formControl: 'min-h-[48px] w-full rounded-lg border-[1.5px] border-[#bfc7d2] bg-white px-3.5 py-2.5 text-[13.5px] text-[#171c1f] outline-none transition-colors focus:border-[#006096]',
  formGroup: 'mb-4',
  formLabel: 'mb-1.5 block text-[12px] font-semibold text-[#3f4851]',
  btnError: 'border-none bg-[#ba1a1a] text-white hover:bg-[#93000a]',
} as const;
